[build]
  command = "${workspaceFolder}build.bat 2>&1"
  isBackground = true
[build.problemMatcher]
#  errorformat = '%f:%l:%c\ %m'
  useStdout = true
[build.problemMatcher.pattern]
 regexp = '^\(.*\):\(\d\+\):\(\d\+\):\s\+\(error\|warning\):\(.*\)$'
 file = 1
 line = 2
 column = 3 
 severity = 4
 message = 5
